### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by thuongleit** [thuongleit/hackernews_flutter#1]
- [x] Create a HackerNews flutter project
- [x] Create TODO list (list of feature to be developed)
- [x] Create first dummy screen of main screen
- [x] Load item into the screen
- [x] Open item in external browser
- [x] Open comment in external screen
- [ ] Save item for reading later
- [ ] Add filter sources to be loaded
- [ ] Notification new items
- [x] About screen
